; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:seeed_xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200

lib_deps = 
    adafruit/adafruit bmp280 library@^3.0.0
    adafruit/adafruit unified sensor@^1.1.15
    sciosense/ScioSense_ENS16x@2.0.5
    adafruit/Adafruit AHTX0@^2.0.6
    adafruit/Adafruit GFX Library@^1.12.6
    zinggjm/GxEPD2@^1.6.9
    bblanchon/ArduinoJson @ ^7.0.0
